# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker:
    # Choose the version of Node you want here
    - image: circleci/android:api-28-node 
  working_directory: ~/repo

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
     # Debug with ssh 
      - add_ssh_keys:
          fingerprints:
            - "SO:ME:FIN:G:ER:PR:IN:T"
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          name: Restore example_project node modules
          keys:
            -  v1-example-{{ checksum "example_project/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-example-
      - run:
          name: Install dependencies
          command: yarn install
      - run:  
          name: Intall dependencies for example project
          command: cd example_project && yarn install
      - run:
          name: Change Permissions
          command: sudo chown -R $(whoami) /usr/local
      - save_cache:
          name: Save node modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - save_cache:
          name: Save node modules example_project
          paths:
            - example_project/node_modules
          key: v1-example-{{ checksum "example_project/package.json" }}

  tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          name: Restore example_project node modules
          keys:
            - v1-example-{{ checksum "example_project/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-example-
      - run:
          name: Change Permissions
          command: sudo chown -R $(whoami) /usr/local
      - run:
          name:  Update package list
          command: sudo apt-get update
      - run:
          name: Install gems for Integration tests
          command: sudo apt install ruby-full
      - run:
          name: Install fastlane
          command: sudo gem install fastlane -NV
      - run:
          name: Run tests
          command: yarn ci:test # this command will be added to/found in your package.json scripts

  publish:
    <<: *defaults
    steps:
    - checkout
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - restore_cache:
        name: Restore node modules
        keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
    - restore_cache:
        name: Restore example_project node modules
        keys:
          - v1-example-{{ checksum "example_project/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-example-
    # Run semantic-release after all the above is set.
    - run:
        name: Publish to NPM
        command: yarn ci:publish

workflows:
  version: 2
  test_and_release:
    jobs:
      - setup
      - tests:
          requires:
            - setup
      - publish:
          requires:
            - tests
          filters:
            branches:
              only: master
